// flow-typed signature: 6a3cb301426c1b269f6b3a9fa8d4ecff
// flow-typed version: <<STUB>>/find-package_v^1.0.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'find-package'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'find-package' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'find-package/example/nested-dir/more-nested-dir/deeply-nested-dir/find-package-example' {
  declare module.exports: any;
}

declare module 'find-package/test/find-package-with-paths.spec' {
  declare module.exports: any;
}

declare module 'find-package/test/find-package-without-paths.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'find-package/example/nested-dir/more-nested-dir/deeply-nested-dir/find-package-example.js' {
  declare module.exports: $Exports<'find-package/example/nested-dir/more-nested-dir/deeply-nested-dir/find-package-example'>;
}
declare module 'find-package/index' {
  declare module.exports: $Exports<'find-package'>;
}
declare module 'find-package/index.js' {
  declare module.exports: $Exports<'find-package'>;
}
declare module 'find-package/test/find-package-with-paths.spec.js' {
  declare module.exports: $Exports<'find-package/test/find-package-with-paths.spec'>;
}
declare module 'find-package/test/find-package-without-paths.spec.js' {
  declare module.exports: $Exports<'find-package/test/find-package-without-paths.spec'>;
}
